### PR TITLE
move interrupt vector table to interruptmanager

### PR DESCRIPTION
**Pull request by imilk23**
Interrupt vector table should  be manage by InterruptManager instead of DeviceManager

### CODE REVIEW

**Comment by nguyenzung** [comment]
I think we should not manage handlers in InterruptManager, because handlers are the devices. InterruptManager has responsibility to transfer interrupts/exceptions from CPU to the OS. DeviceManager is used for the logic managing devices.

**Comment by imilk23** [comment]
> I think we should not manage handlers in InterruptManager, because handlers are the devices. InterruptManager has responsibility to transfer interrupts/exceptions from CPU to the OS. DeviceManager is used for the logic managing devices.

I agreed DeviceManager is used for the logic managing devices. However, DeviceManager should register an interrupt handler to InterruptManager when it wants to handle an interrupt event. Otherwise, there are many types of interrupts that are not related to devices and not all devices want to handle interrupts. Please consider my point of view.

**Comment by mountto** [comment]
các develop, viết tính năng cuộn màn hình, để khỏi mất text trên màn hình ạ

**Comment by imilk23** [comment]
> các develop, viết tính năng cuộn màn hình, để khỏi mất text trên màn hình ạ

mình nghĩ bạn nên vào phần Issues và tạo New Issue

**Comment by nguyenzung** [comment]
> các develop, viết tính năng cuộn màn hình, để khỏi mất text trên màn hình ạ

Có cuộn màn hình rồi bạn

**Pull request closed without merging**
