### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by mountto**

### CODE REVIEW

**Comment by nguyenzung** [comment]
It is really nice, indeed. Please add preprocessors to define that feature because it is available when we use QEMU.

**Comment by mountto** [comment]
Làm như nào nguyenzung , chưa hiểu lắm

**Comment by vuhailongkl97** [comment]
@nguyenzung I think it still works with real hardware because the QEMU simulates the board's serial port, it may be a development board with an exported serial port :D. Should we create a .config file to enable/disable the feature?

**Comment by mountto** [comment]
Ta chỉ cần thêm qemu_demo: trong Makefile được ko
qemu_demo:  $(TARGET)
	qemu-system-x86_64 -serial file:kos_serial.log -no-reboot -no-shutdown -cdrom $<

**Comment by nguyenzung** [comment]
@vuhailongkl97 @murtmeiv I think we should make config file.

**Pull request merged**
